variables:
  - name: project_name
    default_value: "{{ file_name ffizer_dst_folder }}"

  - name: package_name
    default_value: "{{ to_kebab_case project_name }}"

  - name: description
    prompt: "Short description"
    default_value: "A React + PandaCSS app"

  - name: author_name
    prompt: "Author"
    default_value: '{{ env_var "USERNAME" }}'

use_template_dir: true
